//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celular
    {
        public int CelularID { get; set; }
        public Nullable<int> ModTelefoneID { get; set; }
        public Nullable<int> FuncionarioID { get; set; }
        public string Imei { get; set; }
        public string Serial { get; set; }
        public string Numero { get; set; }
    
        public virtual ModTelefone ModTelefone { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
