//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cftv
    {
        public int CftvID { get; set; }
        public Nullable<int> ModCftvID { get; set; }
        public Nullable<int> PlaquetaID { get; set; }
        public string Local { get; set; }
    
        public virtual Plaqueta Plaqueta { get; set; }
        public virtual ModCftv ModCftv { get; set; }
    }
}
