//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtivosDBEntities : DbContext
    {
        public AtivosDBEntities()
            : base("name=AtivosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cadeira> Cadeiras { get; set; }
        public virtual DbSet<Celular> Celulars { get; set; }
        public virtual DbSet<Cftv> Cftvs { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Fabricante> Fabricantes { get; set; }
        public virtual DbSet<Fechadura> Fechaduras { get; set; }
        public virtual DbSet<Fornecedor> Fornecedors { get; set; }
        public virtual DbSet<ModMovel> ModMovels { get; set; }
        public virtual DbSet<ModNobreak> ModNobreaks { get; set; }
        public virtual DbSet<ModPilha> ModPilhas { get; set; }
        public virtual DbSet<ModSoftware> ModSoftwares { get; set; }
        public virtual DbSet<ModSwitch> ModSwitches { get; set; }
        public virtual DbSet<ModTeclado> ModTecladoes { get; set; }
        public virtual DbSet<ModTelefone> ModTelefones { get; set; }
        public virtual DbSet<Nobreak> Nobreaks { get; set; }
        public virtual DbSet<Ocorrencia> Ocorrencias { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Pilha> Pilhas { get; set; }
        public virtual DbSet<Setor> Setors { get; set; }
        public virtual DbSet<Switch> Switches { get; set; }
        public virtual DbSet<Teclado> Tecladoes { get; set; }
        public virtual DbSet<Window> Windows { get; set; }
        public virtual DbSet<Plaqueta> Plaquetas { get; set; }
        public virtual DbSet<ModImpressora> ModImpressoras { get; set; }
        public virtual DbSet<ModCftv> ModCftvs { get; set; }
        public virtual DbSet<Ramal> Ramals { get; set; }
        public virtual DbSet<ModPc> ModPcs { get; set; }
        public virtual DbSet<Pc> Pcs { get; set; }
        public virtual DbSet<ModMonitor> ModMonitors { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Movei> Moveis { get; set; }
        public virtual DbSet<Impressora> Impressoras { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
    }
}
