//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModImpressora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModImpressora()
        {
            this.Impressoras = new HashSet<Impressora>();
        }
    
        public int ModImpressoraID { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Fabricante { get; set; }
        public Nullable<int> Fornecedor { get; set; }
    
        public virtual Fabricante Fabricante1 { get; set; }
        public virtual Fornecedor Fornecedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impressora> Impressoras { get; set; }
    }
}
