//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModNobreak
    {
        public int ModNobreakID { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> FabricanteID { get; set; }
    
        public virtual Fabricante Fabricante { get; set; }
    }
}
