//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocorrencia
    {
        public int OcorrenciaID { get; set; }
        public Nullable<int> PlaquetaID { get; set; }
        public string Descrição { get; set; }
        public Nullable<int> FuncionarioID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Plaqueta Plaqueta { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
