//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pc
    {
        public int PcID { get; set; }
        public Nullable<int> FuncionarioID { get; set; }
        public Nullable<int> ModPcID { get; set; }
        public string NomePc { get; set; }
        public string Série { get; set; }
        public int PlaquetaID { get; set; }
        public bool Auditorado { get; set; }
        public Nullable<System.DateTime> DataCompra { get; set; }
        public Nullable<float> Preço { get; set; }
    
        public virtual ModPc ModPc { get; set; }
        public virtual Plaqueta Plaqueta { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
