//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teclado
    {
        public int TecladoID { get; set; }
        public Nullable<int> FuncionarioID { get; set; }
        public Nullable<int> FabricanteID { get; set; }
        public Nullable<int> ModTecladoID { get; set; }
        public Nullable<int> PlaquetaID { get; set; }
    
        public virtual Fabricante Fabricante { get; set; }
        public virtual ModTeclado ModTeclado { get; set; }
        public virtual Plaqueta Plaqueta { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
